title: CCS Specs
repository: clics/ccs-specs
lang: en
description: CCS Specs

readme_index:
  with_frontmatter: true

theme: null

remote_theme: rundocs/jekyll-rtd-theme

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default-with-js"

plugins:
  - jekyll-remote-theme

markdown: CommonMarkGhPages
commonmark:
  options: ['SMART']
  extensions: ['table']
